<?php use Light\Paginator;

echo $this->partial('header'); ?>

<style>
  nav.navbar {
    display: none;
  }
</style>

<div class="container">

    <div class="panel box-shadow">

        <form data-form-table="true">

            <input type="hidden" value="<?php echo $this->page; ?>" name="page" />

            <div class="panel-body">

                <?php echo $this->partial('table/partial/filter'); ?>

                <?php if ($this->paginator->count()) : ?>

                    <table class="table table-striped table-hover">

                        <?php echo $this->partial('table/partial/head', ['controls' => $this->controls, 'header' => $this->header]); ?>

                        <tbody>

                        <?php /** @var \Light\Model $row */ ?>
                        <?php foreach ($this->paginator->getItems() as $row) : ?>

                            <tr>
                                <?php echo $this->partial('table/partial/row', ['header' => $this->header, 'row' => $row]); ?>
                                <?php echo $this->partial('table/partial/controls', ['controls' => $this->controls, 'controller' => $this->controller, 'row' => $row, 'elementName' => $this->elementName]); ?>
                            </tr>

                        <?php endforeach; ?>

                        </tbody>

                    </table>

                <?php else: ?>

                    <?php echo $this->partial('table/partial/empty', ['header' => $this->header]); ?>

                <?php endif; ?>

            </div>

            <?php echo $this->paginator->render(); ?>

        </form>

    </div>

</div>
