<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' />

    <?php echo $this->partial('common/layout/assets'); ?>
    <?php $title = \Light\Front::getInstance()->getConfig()['light']['admin']['title'] ?? 'Light.Admin'; ?>

    <title>Auth - <?php echo $title; ?></title>

</head>
<body>

<div class="container">

    <div class="row">

        <div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">

            <div class="col-xs-12">

                <br>

                <h2 class="text-center lead">
                    <?php echo $title; ?>
                </h2>

                <br>

            </div>

            <div class="col-xs-12">

                <form role="form" method="post">

                    <div class="panel panel-default box-shadow">

                        <div class="panel-body">

                            <div class="row">

                                <div class="col-xs-12">

                                    <div class="form-group">
                                        <div class="input-group">
                                            <span class="input-group-addon bmd-addon">
                                                <i class="bmd-icon material-icons">account_circle</i>
                                            </span>
                                            <div class="bmd-field-group">
                                                <input type="text" class="bmd-input" required="required" name="login">
                                                <span class="bmd-bar"></span>
                                                <label class="bmd-label">Логин</label>
                                            </div>
                                        </div>
                                    </div>

                                </div>

                                <div class="col-xs-12">

                                    <div class="form-group">
                                        <div class="input-group">
                                            <span class="input-group-addon bmd-addon">
                                                <i class="bmd-icon material-icons">lock</i>
                                            </span>
                                            <div class="bmd-field-group">
                                                <input type="password" class="bmd-input" required="required" name="password">
                                                <span class="bmd-bar"></span>
                                                <label class="bmd-label">Пароль</label>
                                            </div>
                                        </div>
                                    </div>

                                </div>

                            </div>


                            <?php if ($this->error) : ?>
                                <div class="row">
                                    <div class="col-xs-12">
                                        <div class="alert alert-danger">
                                            <?php echo "Логин или пароль неверны" ?>
                                        </div>
                                    </div>
                                </div>
                            <?php endif; ?>

                        </div>

                        <div class="panel-footer text-right">

                            <div class="row">
                                <div class="col-xs-12">
                                    <button class="btn btn-primary bmd-ripple bmd-floating btn-lg" type="submit">Войти</button>
                                </div>
                            </div>

                        </div>
                    </div>

                </form>

            </div>

        </div>
    </div>
</div>

</body>
</html>
