<?php /** @var \Light\Form\Element\DateTime $element */ ?>
<?php $element = $this->element; ?>

<input type="text"
       class="bmd-input"
       autocomplete="off"
       data-datetimepicker="true"
       data-format="<?php echo $element->getFormat(); ?>"
       <?php if ($element->isReadOnly()) : ?>disabled="disabled"<?php endif; ?>
       id="<?php echo $element->getName(); ?>"
       name="<?php echo $element->getName(); ?>"
       value="<?php echo date($element->getPhpFormat(), $element->getValue()); ?>" />

<label class="bmd-label"><?php echo $element->getLabel(); ?></label>
<span class="bmd-bar"></span>
