<?php /** @var \Light\Form\Element\Email $element */ ?>
<?php $element = $this->element; ?>

<input type="email"
       class="form-control"
       <?php if ($element->isReadOnly()) : ?>readonly="readonly"<?php endif; ?>
       id="<?php echo $element->getName(); ?>"
       name="<?php echo $element->getName(); ?>"
       placeholder="<?php echo $element->getPlaceholder(); ?>"
       value="<?php echo htmlspecialchars($element->getValue()); ?>" />
