<?php /** @var \Light\Form\Element\Images $element */ ?>
<?php $element = $this->element; ?>

<div data-element-imagemultiple="true"
     class="imagesingle-container container-fluid"
     data-storage-url="/<?php echo \Light\Front::getInstance()->getConfig()['light']['storage']['route']; ?>"
     data-name="<?php echo $element->getName(); ?>">

    <a data-select="true" class="btn btn-primary bmd-ripple bmd-fab bmd-fab-sm bmd-floating">
        <span class="bmd-icon flaticon-add182"></span>
    </a>

    <div data-image-container="true">

        <?php foreach ($element->getValue() ?? [] as $image) : ?>

            <a class="btn btn-default background-image preview-image-single bmd-floating bmd-ripple"
               data-image-large="<?php echo $image; ?>"
               style="background-image: url('<?php echo $image; ?>');">
                <input name="<?php echo $element->getName(); ?>[]" value="<?php echo $image; ?>" type="hidden" />
            </a>

        <?php endforeach; ?>

    </div>

    <script type="text/html" data-template="true">
        <a class="btn btn-default background-image preview-image-single bmd-floating bmd-ripple" style="background-image: url('{{value}}');" data-image-large="{{value}}">
            <input name="<?php echo $element->getName(); ?>[]" value="{{value}}" type="hidden" />
        </a>
    </script>

</div>