<?php /** @var \Light\Form\Element\ElementAbstract $element */ ?>
<?php $element = $this->element; ?>

<label for="<?php echo $element->getName(); ?>" class="control-label bmd-control-label">

    <?php echo $element->getLabel() ?? ucfirst($element->getName()); ?>

    <?php if (!$element->isAllowNull()) : ?>
        <span class="text-danger">*</span>
    <?php endif; ?>

    <?php if ($description = $element->getDescription()) : ?>
        <br><span class="text-info small"><?php echo $description; ?></span>
    <?php endif; ?>

</label>