<?php

$selectedLanguage = [
    'title' => 'Все языки',
    'value' => $this->filter['value'],
    'enabled' => true
];

$languages = [];

$languageModelClassName = implode('\\', [
    \Light\Front::getInstance()->getConfig()['light']['loader']['namespace'],
    'Model',
    'Language'
]);

foreach ($languageModelClassName::fetchAll() as $language) {

    $languages[] = [
        'title' => $language->title,
        'value' => $language->id,
        'enabled' => $language->enabled
    ];

    if ($this->filter['value'] == $language->id) {
        $selectedLanguage = [
            'title' => $language->title,
            'value' => $language->id,
            'enabled' => $language->enabled
        ];
    }
}

?>

<div class="form-group">

    <div class="dropdown bmd-select form-control" data-control-select="true">

        <a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" role="button" aria-expanded="false">
            <span class="bmd-selected-value"><?php echo $selectedLanguage['title']; ?> <?php if (!$selectedLanguage['enabled']) : ?>(выключен)<?php endif; ?></span>
            <span class="caret"></span>
            <input name="filter[<?php echo $this->filter['name']; ?>]" value="<?php echo $this->filter['value']; ?>" type="hidden" />
        </a>

        <ul class="dropdown-menu">

            <li><a data-option="" data-value="Все языки">Все языки</a></li>
            <li class="divider"></li>

            <?php foreach ($languages as $language) : ?>

                <li>

                    <a <?php if ($this->filter['value'] == $language['value']) : ?> class="bmd-bg-primary bmd-text-grey-50" <?php endif; ?>
                        data-option="<?php echo $language['value']; ?>"
                        data-value="<?php echo $language['title']; ?> <?php if (!$language['enabled']) : ?>(выключен)<?php endif; ?>">

                        <?php echo $language['title']; ?> <?php if (!$language['enabled']) : ?>(выключен)<?php endif; ?>
                    </a>
                </li>

            <?php endforeach; ?>

        </ul>
        <span class="bmd-bar"></span>
    </div>

</div>