<?php

$emptyRow = new stdClass();
$emptyRow->title = 'Выберете запись';
$emptyRow->id = null;

$selectedRow = null;

foreach ($this->filter['model'] as $model) {
    if ($this->filter['value'] == $model->id) {
        $selectedRow = $model;
    }
}

if (!$selectedRow) {
    $selectedRow = $emptyRow;
}

?>

<div class="form-group">

    <div class="dropdown bmd-select form-control" data-control-select="true">

        <a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" role="button" aria-expanded="false">
            <span class="bmd-selected-value"><?php echo $selectedRow->title; ?></span>
            <span class="caret"></span>
            <input name="filter[<?php echo $this->filter['name']; ?>]" value="<?php echo $selectedRow->id; ?>" type="hidden" />
        </a>

        <ul class="dropdown-menu">

            <li><a data-option="<?php echo $emptyRow->id; ?>" data-value="<?php echo $emptyRow->title; ?>"><?php echo $emptyRow->title; ?></a></li>
            <li class="divider"></li>

            <?php foreach ($this->filter['model'] as $model) : ?>

                <li>

                    <a <?php if ($this->filter['value'] == $model->id) : ?> class="bmd-bg-primary bmd-text-grey-50" <?php endif; ?>
                        data-option="<?php echo $model->id; ?>"
                        data-value="<?php echo $model->{$this->filter['field']}; ?>">

                        <?php echo $model->{$this->filter['field']}; ?>
                    </a>
                </li>

            <?php endforeach; ?>

        </ul>
        <span class="bmd-bar"></span>
    </div>

</div>