
<div class="form-group">

    <div class="input-group">

        <span class="input-group-addon bmd-addon">
            <i class="bmd-icon material-icons">search</i>
        </span>

        <div class="bmd-field-group">

            <input name="filter[<?php echo $this->filter['name']; ?>]"
                   type="text"
                   class="bmd-input"
                   value="<?php echo $this->filter['value']; ?>"/>

            <span class="bmd-bar"></span>
            <label class="bmd-label">Поиск...</label>

        </div>
    </div>
</div>